### ISSUE TITLE
socket hang up error

### ISSUE THREAD

**Issue by do-web** [mattcg/socks5-https-client#22]
`
      var form = new FormData();

  
            form.append('file', fs.createReadStream('./test.jpg'), {
                filename: 'test.jpg',
                contentType: 'image/jpeg'
            });

var req = request({
                url: 'https://myserver.com/fileupload',
                agentClass: Agent,
                agentOptions: {
                    socksHost: 'torproxy',
                    socksPort: 9050
                },
                method: 'POST',
                followRedirect: false,
                headers: Object.assign({
                    'cookie': session.cookies.join(';'),
                    'user-agent': this.userAgent,
                    'connection': 'keep-alive',
                }, form.getHeaders())
            })

            form.pipe(req);

            req.on('response', function(response, body) {
                console.log(response.statusCode);

            });
`

I get the fallowing error:

Error: socket hang up
    at createHangUpError (_http_client.js:343:15)
    at Socks5ClientSocket.socketOnEnd (_http_client.js:435:23)
    at emitNone (events.js:105:13)
    at Socks5ClientSocket.emit (events.js:207:7)

**Comment by kirovilya** [comment]
Hello. Did you solve your error?

**Comment by do-web** [comment]
Hi use now this https://github.com/do-web/curl-request

**Comment by kirovilya** [comment]
Hm... console tool for send files... strange...
ok, I try it.
thank you
