### ISSUE TITLE
https not supported

### ISSUE THREAD

**Issue by lalop** [mattcg/socks5-https-client#4]
Hello,

I'm trying to make an https request with your lib but I get this error 
```
_http_client.js:75
    throw new Error('Protocol "' + protocol + '" not supported. ' +
          ^
Error: Protocol "https:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:75:11)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Object.exports.request (/Users/sam/Workspace/vnzl/image_crawler_discogs/node_modules/socks5-https-client/index.js:27:15)
    at exports.OAuth._createClient (/Users/sam/Workspace/vnzl/image_crawler_discogs/oauth/index.js:259:20)
    at exports.OAuth._performSecureRequest (/Users/sam/Workspace/vnzl/image_crawler_discogs/oauth/index.js:374:19)
    at exports.OAuth.get (/Users/sam/Workspace/vnzl/image_crawler_discogs/oauth/index.js:490:15)
    at DiscogsOauth.getImage (/Users/sam/Workspace/vnzl/image_crawler_discogs/discogs.js:63:18)
    at Object.cb (/Users/sam/Workspace/vnzl/image_crawler_discogs/discogs.js:107:14)
    at Statement.<anonymous> (/Users/sam/Workspace/vnzl/image_crawler_discogs/db.js:55:15)
```

I can make request on https with the node library so I don't understand why I couldn't here.

Samuel

**Comment by mattcg** [comment]
This is a problem with node v0.12.0. Try the latest version of this library (v1.0.0). I've just pushed a fix.

**Comment by lalop** [comment]
perfect
thank you
