### ISSUE TITLE
_tls_legacy.js ssl is null

### ISSUE THREAD

**Issue by lalop** [mattcg/socks5-https-client#5]
Not sure if the issue is in the node tls code or in your package but I get this error
```
_tls_legacy.js:825
  var err = this.ssl.error;
                    ^
TypeError: Cannot read property 'error' of null
    at SecurePair.error (_tls_legacy.js:825:21)
    at EncryptedStream.CryptoStream._done (_tls_legacy.js:487:22)
    at EncryptedStream.onCryptoStreamFinish (_tls_legacy.js:134:10)
    at EncryptedStream.g (events.js:199:16)
    at EncryptedStream.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at EncryptedStream.Writable.end (_stream_writable.js:459:5)
    at EncryptedStream.CryptoStream.end (_tls_legacy.js:426:31)
    at Socket.onend (_stream_readable.js:505:10)
```

That happens when I handle an error ```socket hang up```

Let me know if I should open this issue at the nodejs project level

**Comment by lalop** [comment]
The issue is on the nodejs project https://github.com/joyent/node/issues/8623
