### ISSUE TITLE
Protocol "https:" not supported. Expected "http:".

### ISSUE THREAD

**Issue by polkovnikov-ph** [mattcg/socks5-https-client#6]
```_http_client.js:50
    throw new Error('Protocol "' + protocol + '" not supported. ' +
          ^
Error: Protocol "https:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:50:11)
    at Object.exports.request (http.js:30:10)
    at Object.exports.request (https.js:115:15)
    at Object.exports.request (d:\...\node_modules\socks5-https-client\index.js:27:15)
    at Object.exports.get (d:\...\node_modules\socks5-https-client\index.js:31:20)```
	
on `https://wtfismyip.com/json` URL.

Windows 7, iojs 1.2.0

**Comment by polkovnikov-ph** [comment]
Sorry, missed the fact 1.0 version is not on npm still.

**Comment by mattcg** [comment]
Did you update your package.json? The version currently on npm is 1.0.1.

**Comment by polkovnikov-ph** [comment]
Cleared dependencies, but could've made a mistake somewhere else. Anyway, it works fine now.

**Comment by mattcg** [comment]
Cool :smile_cat:, thanks
