### ISSUE TITLE
COMODO certificates are not accepted

### ISSUE THREAD

**Issue by mjesun** [mattcg/socks5-https-client#7]
Considering a request like this one:
```javascript
{
	method: 'GET',
	protocol: 'https:',
	hostname: 'codewars.co',
	path: '/',
	headers: {
		'Cache-Control': 'no-cache',
		'Host': 'codewars.co',
		'User-Agent': 'Node 0.12'
	}
}
```

Using the `https` module works, but using the `socks5-https-client` doesn't. The error I get is this one:
```
Error: 140688461326144:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s23_clnt.c:770:

    at Error (native)
    at SlabBuffer.use (_tls_legacy.js:62:18)
    at CleartextStream.read [as _read] (_tls_legacy.js:280:29)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (_tls_legacy.js:194:25)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at EncryptedStream.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
```

Which after some investigation I've found it's related to "COMODO ECC Domain Validation Secure Server CA 2" certificates; which is the one that CloudFlare uses, making this bug to be potentially affecting a lot of sites.

Note: I know that https://codewars.co returns a CloudFlare error; I intentionally chose this one to make the test. Also note I'm not related at all with that site; I just googled until I found a site behind CloudFlare, using HTTPS :)

**Comment by mjesun** [comment]
Wow! That was FAST! :) Thanks a lot

**Comment by mattcg** [comment]
Something I've been meaning to do for a while! Enjoy, and thanks for filing this issue. Very detailed!
